### ISSUE TITLE
Suggestion: Consider using consts over static readonly properties

### ISSUE THREAD

**Issue by tkp1n** [tmds/Tmds.LibC#49]
I'm sure there is a reasoning behind the current convention. I would however argue that using `const`s (over static readonly properties) for values defined in headers is generally more usefull, as it allows the value to be used in switch statements/expressions and as assignments for enum values.

#### consider preferring this:
```csharp
public const byte IORING_OP_NOP = 0;
public const byte IORING_OP_READV = 1;
public const byte IORING_OP_WRITEV = 2;
public const byte IORING_OP_FSYNC = 3;
```

#### over this:
```csharp
public static byte IORING_OP_NOP => 0;
public static byte IORING_OP_READV => 1;
public static byte IORING_OP_WRITEV => 2;
public static byte IORING_OP_FSYNC => 3;
```

#### which would allow defining enum values...
```csharp
using static Tmds.Linux.LibC;

enum Opcode : byte 
{
    Nop = IORING_OP_NOP,
    ReadV = IORING_OP_READV,
    WriteV = IORING_OP_WRITEV,
    FSync = IORING_OP_FSYNC 
}
```

#### ...or using them in `switch` statements or expressions
```csharp
public static SocketError GetSocketErrorForErrno(int errno) =>
    errno switch {
        EACCES => SocketError.AccessDenied,
        EADDRINUSE => SocketError.AddressAlreadyInUse,
        _ => throw null
};
```

@tmds let me know how you think about this

**Comment by tmds** [comment]
> I'm sure there is a reasoning behind the current convention.

The reason is that we don't want the compiler to consider these constants, because they might change between platforms. It is not the case for the IORING_OPs, but it is the case for the errno values.
By making these static properties, the compiler doesn't consider them constants, but we let the JIT inline them as constants.

> let me know how you think about this

I prefer for simplicity and consistency to keep using static properties in Tmds.LibC.

These are two things you could do:
- Implement the enums as structs.
- Implement the enums as enums, and use internal map methods. Probably these mappings are inlineable.

I'd only do this for enums that are part of the public API.

**Comment by tkp1n** [comment]
I knew there was a reason, thanks for clarifying.. I didn't think of that
